name: Build ms-tpm-20-ref (Windows x86_64 - MSYS2)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows-msys2:
    runs-on: windows-latest
    name: Build on Windows (MSYS2 / x86_64)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2 (install base)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false

      - name: Update MSYS2 and install packages (ensure autoconf etc)
        shell: bash
        run: |
          set -euo pipefail
          # Use MSYS2's bash. msys2 gets installed to C:\msys64 on windows-latest.
          MSYS_BASH="C:/msys64/usr/bin/bash.exe"
          if [ ! -x "$MSYS_BASH" ]; then
            echo "MSYS2 bash not found at $MSYS_BASH"
            exit 1
          fi

          # Run pacman commands inside MSYS2 MINGW64 environment
          "$MSYS_BASH" -lc 'export MSYSTEM=MINGW64; set -euo pipefail; pacman -Syuu --noconfirm || true; pacman -Su --noconfirm || true; pacman -S --noconfirm --needed autoconf automake libtool autoconf-archive m4 make pkg-config gawk mingw-w64-x86_64-toolchain mingw-w64-x86_64-openssl; echo "=== VERSIONS ==="; uname -a; gcc --version || true; autoconf --version || true; automake --version || true; pacman -Qi autoconf || true'

      - name: Build (autoreconf + configure + make) in MINGW64
        shell: bash
        run: |
          set -euo pipefail
          MSYS_BASH="C:/msys64/usr/bin/bash.exe"
          "$MSYS_BASH" -lc 'export MSYSTEM=MINGW64; set -euo pipefail; cd TPMCmd; rm -rf autom4te.cache aclocal.m4 configure config.status config.log || true; autoreconf -fi; ./configure --host=x86_64-w64-mingw32 --prefix=/mingw64; make -j$(nproc)'

      - name: Collect binaries
        shell: bash
        run: |
          set -euo pipefail
          MSYS_BASH="C:/msys64/usr/bin/bash.exe"
          "$MSYS_BASH" -lc 'export MSYSTEM=MINGW64; set -euo pipefail; mkdir -p out; find . -type f -iname "*.exe" -print0 | xargs -0 -I{} cp -v {} out/ || true; ls -l out || true'

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ms-tpm-20-ref-windows-x86_64
          path: out