name: Build on Windows (MSYS2/x86_64)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-msys2:
    runs-on: windows-latest
    env:
      MSYSTEM: MINGW64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            base-devel
            mingw-w64-x86_64-toolchain
            autoconf
            automake
            libtool
            pkg-config
            openssl
            gawk

      - name: List repo contents
        run: ls -R "$GITHUB_WORKSPACE"

      - name: Build ms-tpm-20-ref
        shell: "msys2 { msystem: MINGW64 }"
        run: |
          set -euo pipefail
          cd "$GITHUB_WORKSPACE/TPMCmd"
          rm -rf autom4te.cache aclocal.m4 configure config.status config.log || true
          autoreconf -fi
          ./configure --host=x86_64-w64-mingw32 --prefix=/mingw64
          make -j$(nproc)

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tpmc-executables
          path: "**/TPMCmd/*.exe"