# .github/workflows/build-windows.yml
name: Build ms-tpm-20-ref (Windows x86_64 - MSYS2)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows-msys2:
    name: Build on Windows (MSYS2 / x86_64)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            autoconf
            automake
            libtool
            pkg-config
            make
            gcc
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-openssl
            autoconf-archive
      - name: Show tool versions
        shell: bash
        run: |
          uname -a
          gcc --version
          autoconf --version
          automake --version
          pkg-config --version

      - name: Build (autoreconf + configure + make)
        shell: bash
        run: |
          cd TPMCmd
          rm -rf autom4te.cache aclocal.m4 configure config.status
          autoreconf -fi
          ./configure --host=x86_64-w64-mingw32 --prefix=/mingw64
          make -j$(nproc)

      - name: Collect binaries
        shell: bash
        run: |
          # 輸出可能在 TPMCmd 的子目錄(視 Makefile)
          # 調整路徑以收集主要執行檔（示例）
          mkdir -p out
          # 嘗試找到任何 exe 生成
          find . -name "*.exe" -type f -print | xargs -I{} cp {} out/ || true
          ls -l out || true

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ms-tpm-20-ref-windows-x86_64
          path: out