name: Build on Windows (MSYS2/x86_64)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup MSYS2
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            base-devel
            mingw-w64-x86_64-toolchain
            autoconf
            automake
            libtool
            pkg-config
            openssl
            gawk

      # 3. Build TPMCmd
      - name: Build TPMCmd
        shell: msys2 { msystem: MINGW64 }
        run: |
          cd TPMCmd
          rm -rf autom4te.cache aclocal.m4 configure config.status config.log || true
          autoreconf -fi
          ./configure --host=x86_64-w64-mingw32 --prefix=/mingw64
          make -j$(nproc)