name: Build on Windows (MSYS2/x86_64)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-msys2:
    runs-on: windows-latest
    env:
      MSYSTEM: MINGW64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            base-devel
            mingw-w64-x86_64-toolchain
            autoconf
            automake
            libtool
            pkg-config
            openssl
            gawk

      - name: List repo contents
        run: ls -R "$GITHUB_WORKSPACE"

      - name: Build ms-tpm-20-ref
        shell: bash
        run: |
          set -euo pipefail
          MSYS_BASH="C:/msys64/usr/bin/bash.exe"

          # 嘗試找到 TPMCmd 目錄
          TPMCMD_DIR=$(find "$GITHUB_WORKSPACE" -type d -iname "TPMCmd" | head -n 1)

          if [ -z "$TPMCMD_DIR" ]; then
            echo "ERROR: TPMCmd directory not found in $GITHUB_WORKSPACE"
            ls -la "$GITHUB_WORKSPACE"
            exit 1
          else
            echo "Found TPMCmd at: $TPMCMD_DIR"
          fi

          # 執行 build
          "$MSYS_BASH" -lc "export MSYSTEM=MINGW64; set -euo pipefail; \
            cd \"$TPMCMD_DIR\"; \
            rm -rf autom4te.cache aclocal.m4 configure config.status config.log || true; \
            /c/msys64/mingw64/bin/autoreconf -fi; \
            ./configure --host=x86_64-w64-mingw32 --prefix=/mingw64; \
            make -j\$(nproc)"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tpmc-executables
          path: "**/TPMCmd/*.exe"